version: "3.8"

services:
  webserver1:
    image: lipanski/docker-static-website:latest
    ports:
      - "8081:80"
    volumes:
      - /some/local/web1:/home/static
      - ./httpd.conf:/home/static/httpd.conf:ro
    networks: 
     - network-backend

  webserver2:
    image: lipanski/docker-static-website:latest
    ports:
      - "8082:80"
    volumes:
      - /some/local/web2:/home/static
      - ./httpd.conf:/home/static/httpd.conf:ro
    networks: 
     - network-backend



